### ISSUE TITLE
ESでindex.jsonのsettingsとmappingsが反映されていないかもしれない

### ISSUE THREAD

**Issue by yasuhiroiwaki** [pi-poninc/elastic_search#10]
# ESでindex.jsonのsettingsとmappingsが反映されていないかもしれない
----
- index.jsonを読み込みElasticsearchのindexをcreateした場合
```shell
python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> from elasticsearch import Elasticsearch
>>> with open('index.json', 'r', encoding='utf-8') as f:
...     source = json.load(f)
...
>>> type(source)
<class 'dict'>
>>> import pprint
>>> pprint.pprint(source)
{'mappings': {'_source': {'enabled': 'true'},
              'dynamic': 'true',
              'properties': {'extracted_texts': {'analyzer': 'my_ja_analyzer',
                                                 'index': 'true',
                                                 'search_analyzer': 'my_ja_analyzer',
                                                 'type': 'text'},
                             'pathes': {'index': 'true', 'type': 'text'},
                             'slide_num': {'type': 'float'},
                             'slide_show': {'type': 'float'}}},
 'settings': {'analysis': {'analyzer': {'my_ja_analyzer': {'char_filter': ['kuromoji_iteration_mark'],
                                                           'filter': ['kuromoji_baseform',
                                                                      'kuromoji_part_of_speech',
                                                                      'ja_stop',
                                                                      'kuromoji_number',
                                                                      'kuromoji_stemmer'],
                                                           'tokenizer': 'kuromoji_tokenizer',
                                                           'type': 'custom'}}}}}
>>>
>>>
>>> client = Elasticsearch('elasticsearch')
>>> client.indices.create(index='index3', body=source)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/indices.py", line 124, in create
    "PUT", _make_path(index), params=params, headers=headers, body=body
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/transport.py", line 458, in perform_request
    raise e
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/transport.py", line 426, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/http_urllib3.py", line 277, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/base.py", line 331, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.TransportError: TransportError(500, 'class_cast_exception', "class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')")
```

- parseの問題なのかとりあえず投入できていない
- コードの中では以下のtry ~ exceptで例外処理をしているが、全ての例外を捕捉している訳ではないので、単にスキップされているだけに見える
-  https://github.com/pi-poninc/elastic_search/blob/b2018826fa055361894491aac89dd115d040c31a/src/app/apiv1/testapp.py#L43
- ちなみに以下の様に、settingsだけは登録できる
```shell
>>> settings = {'settings': source['settings']}
>>> pprint.pprint(settings)
{'settings': {'analysis': {'analyzer': {'my_ja_analyzer': {'char_filter': ['kuromoji_iteration_mark'],
                                                           'filter': ['kuromoji_baseform',
                                                                      'kuromoji_part_of_speech',
                                                                      'ja_stop',
                                                                      'kuromoji_number',
                                                                      'kuromoji_stemmer'],
                                                           'tokenizer': 'kuromoji_tokenizer',
                                                           'type': 'custom'}}}}}
>>> client.indices.create(index='index3', body=settings)
/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/base.py:208: ElasticsearchWarning: the default number of shards will change from [5] to [1] in 7.0.0; if you wish to continue using the default of [5] shards, you must manage this on the create index request or with an index template
  warnings.warn(message, category=ElasticsearchWarning)
/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/base.py:208: ElasticsearchWarning: Sun, 19 Sep 2021 16:44:47 GMT
  warnings.warn(message, category=ElasticsearchWarning)
{'acknowledged': True, 'shards_acknowledged': True, 'index': 'index3'}
```

**Comment by yasuhiroiwaki** [comment]
- どうやらelasticsearchのversionによってmappingのkeyが違う模様
- version7.0以降では _doc が廃止された
- version7.0よりも前は _docが必要らしい
- https://www.elastic.co/guide/en/elasticsearch/reference/7.14/removal-of-types.html
- 古い方は以下の様な構造にすればうまくいきそう
```shell
mappings = {
    '_doc': {
        'properties': {
            'field1': {
                'type': 'long'
            },
            ...
        }
    }
}
```

**Comment by yasuhiroiwaki** [comment]
- elasticsearchのversionを6.6.0から7.9.2にすることで解消した
- elasticsearchのenvironmentに指定が色々と必要だった(@docker-compose.yml)
- 以下の通り、index.jsonの投入はできた
```shell
# python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from elasticsearch import Elasticsearch
>>> es = Elasticsearch('elasticsearch')
>>> mappings = es.indices.get_mapping(index='index3')
>>> mappings
{'index3': {'mappings': {'dynamic': 'true', 'properties': {'extracted_texts': {'type': 'text', 'analyzer': 'my_ja_analyzer'}, 'pathes': {'type': 'text'}, 'slide_num': {'type': 'float'}, 'slide_show': {'type': 'float'}}}}}
>>>
```

**Comment by yasuhiroiwaki** [comment]
**環境差分の問題で解消されたと判断し、issueをcloseする**
